# Generated by Django 3.2.7 on 2021-09-13 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Txns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_hash', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=50)),
                ('block', models.BigIntegerField()),
                ('age', models.DateTimeField()),
                ('txn_from', models.CharField(max_length=255)),
                ('txn_to', models.CharField(max_length=255)),
                ('value', models.FloatField()),
                ('txn_fee', models.FloatField()),
            ],
        ),
    ]
