# Generated by Django 3.2.7 on 2021-09-16 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0002_txns'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('txn_hash', models.CharField(max_length=255)),
                ('age', models.DateTimeField()),
                ('txn_from', models.CharField(max_length=255)),
                ('txn_to', models.CharField(max_length=255)),
                ('value', models.FloatField()),
                ('token', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='txns',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
